import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { createCommand } from '../src/commands/create.js';
import { CLI_VERSION } from '../src/version.js';

describe('create command', () => {
  it('creates a tool-agent project', async () => {
    const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'agent-creator-'));
    const previous = process.cwd();
    process.chdir(dir);
    try {
      await createCommand('demo-agent', { template: 'tool-agent', packageManager: 'npm' });
      await expect(fs.access(path.join(dir, 'demo-agent', 'agent.config.ts'))).resolves.toBeUndefined();
      await expect(fs.access(path.join(dir, 'demo-agent', 'src/agent/orchestrator.ts'))).resolves.toBeUndefined();
      const config = await fs.readFile(path.join(dir, 'demo-agent', 'agent.config.ts'), 'utf8');
      expect(config).toContain("configVersion: '0.1'");
      expect(config).toContain(`templateVersion: '${CLI_VERSION}'`);
      expect(config).toContain("generatedBy:");
      const readme = await fs.readFile(path.join(dir, 'demo-agent', 'README.md'), 'utf8');
      expect(readme).toContain(`Generated by Agent Creator v${CLI_VERSION}.`);
      const generatedPackageJson = JSON.parse(await fs.readFile(path.join(dir, 'demo-agent', 'package.json'), 'utf8')) as { version: string };
      expect(generatedPackageJson.version).toBe(CLI_VERSION);
    } finally {
      process.chdir(previous);
    }
  });
});
