import type { AgentConfig } from '../types/config.js';
import type { ModelGenerateInput, ModelGenerateOutput, ModelProvider } from './modelProvider.js';

interface ChatCompletionResponse {
  choices?: Array<{
    message?: {
      content?: string;
    };
  }>;
}

export function createOpenAICompatibleProvider(config: AgentConfig): ModelProvider {
  return {
    async generate(input) {
      const apiKey = process.env.OPENAI_API_KEY;
      const baseUrl = process.env.LLM_BASE_URL || 'https://api.openai.com/v1';
      const model = process.env.LLM_MODEL || config.model.defaultModel;

      if (!apiKey) throw new Error('model_config_missing: OPENAI_API_KEY is required.');
      if (!model) throw new Error('model_config_missing: LLM_MODEL or config.model.defaultModel is required.');

      const response = await fetch(`${baseUrl.replace(/\/$/, '')}/chat/completions`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${apiKey}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          model,
          messages: buildMessages(input),
          temperature: 0.2,
        }),
        signal: AbortSignal.timeout(config.model.timeoutMs),
      });

      if (!response.ok) {
        const text = await response.text();
        throw new Error(`model_error: ${response.status} ${text}`);
      }

      const data = await response.json() as ChatCompletionResponse;
      const text = data.choices?.[0]?.message?.content;
      if (!text) throw new Error('model_error: empty model response.');
      return { text };
    },
  };
}

function buildMessages(input: ModelGenerateInput): Array<{ role: 'system' | 'user'; content: string }> {
  return [
    {
      role: 'system',
      content: [
        'You are a service Agent generated by Agent Creator.',
        'Return concise, useful responses.',
        'Do not invent tool results; tools are executed by the runtime before LLM steps.',
      ].join(' '),
    },
    {
      role: 'user',
      content: JSON.stringify({ task: input.task, input: input.input, memory: input.memory ?? [] }),
    },
  ];
}
