import type { TemplateFile } from '../../types/template.js';

export function toolAgentFiles(projectName: string): TemplateFile[] {
  const safeName = projectName.replace(/[^a-zA-Z0-9_-]/g, '-');
  return [
    { path: 'package.json', content: packageJson(safeName) },
    { path: 'tsconfig.json', content: tsconfigJson() },
    { path: '.gitignore', content: gitignore() },
    { path: '.env.example', content: 'AGENT_ENV=local\n' },
    { path: 'README.md', content: generatedReadme(safeName) },
    { path: 'agent.config.ts', content: agentConfig(safeName) },
    { path: 'src/index.ts', content: sourceIndex() },
    { path: 'src/dev.ts', content: devConsole() },
    { path: 'src/types/agent.ts', content: agentTypes() },
    { path: 'src/types/tool.ts', content: toolTypes() },
    { path: 'src/types/config.ts', content: configTypes() },
    { path: 'src/types/trace.ts', content: traceTypes() },
    { path: 'src/schemas/output.schema.ts', content: outputSchema() },
    { path: 'src/schemas/config.schema.ts', content: configSchema() },
    { path: 'src/agent/inputAnalyzer.ts', content: inputAnalyzer() },
    { path: 'src/agent/intentRouter.ts', content: intentRouter() },
    { path: 'src/agent/guard.ts', content: guard() },
    { path: 'src/agent/planner.ts', content: planner() },
    { path: 'src/agent/executor.ts', content: executor() },
    { path: 'src/agent/orchestrator.ts', content: orchestrator() },
    { path: 'src/agent/toolRegistry.ts', content: toolRegistry() },
    { path: 'src/agent/outputValidator.ts', content: outputValidator() },
    { path: 'src/agent/errorRecovery.ts', content: errorRecovery() },
    { path: 'src/model/modelProvider.ts', content: modelProvider() },
    { path: 'src/model/mockLLM.ts', content: mockLLM() },
    { path: 'src/memory/memoryManager.ts', content: memoryManager() },
    { path: 'src/tools/index.ts', content: toolsIndex() },
    { path: 'src/tools/weather.ts', content: weatherTool() },
    { path: 'src/tools/math.ts', content: mathTool() },
    { path: 'src/traces/traceLogger.ts', content: traceLogger() },
    { path: 'src/traces/traceStore.ts', content: traceStore() },
    { path: 'src/utils/id.ts', content: idUtil() },
    { path: 'src/utils/time.ts', content: timeUtil() },
    { path: 'src/utils/json.ts', content: jsonUtil() },
    { path: 'src/utils/errors.ts', content: errorsUtil() },
    { path: 'src/utils/logger.ts', content: loggerUtil() },
    { path: 'tests/config.test.ts', content: configTest() },
    { path: 'tests/toolRegistry.test.ts', content: toolRegistryTest() },
    { path: 'tests/orchestrator.test.ts', content: orchestratorTest() },
    { path: 'examples/basic.ts', content: exampleBasic() },
    { path: 'examples/tool-call.ts', content: exampleToolCall() },
    { path: '.agent-traces/.gitkeep', content: '' },
  ];
}

function packageJson(projectName: string): string {
  return `${JSON.stringify({
    name: projectName,
    version: '0.1.0',
    type: 'module',
    scripts: {
      dev: 'tsx src/dev.ts',
      build: 'tsc',
      start: 'node dist/src/index.js',
      test: 'vitest run',
      validate: 'agent validate',
    },
    dependencies: { zod: '^3.23.8' },
    devDependencies: {
      '@types/node': '^20.14.12',
      tsx: '^4.16.2',
      typescript: '^5.5.4',
      vitest: '^2.0.5',
    },
  }, null, 2)}\n`;
}

function tsconfigJson(): string {
  return `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "lib": ["ES2022"],
    "strict": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "skipLibCheck": true,
    "outDir": "dist",
    "rootDir": "."
  },
  "include": ["agent.config.ts", "src/**/*.ts", "tests/**/*.ts", "examples/**/*.ts"],
  "exclude": ["dist", "node_modules"]
}
`;
}

function gitignore(): string {
  return `node_modules/
dist/
coverage/
.DS_Store
.agent-traces/*.json
`;
}

function generatedReadme(projectName: string): string {
  return `# ${projectName}

Generated by Agent Creator v0.1.

This project is a runnable tool-agent skeleton with mock tools, mock LLM, trace logging, validation, and tests.

## Commands

\`\`\`bash
npm install
npm run dev
npm run build
npm test
agent validate
agent trace --latest
agent add tool calendar
\`\`\`

## Runtime Flow

\`\`\`txt
input -> inputAnalyzer -> intentRouter -> guard -> planner -> executor -> outputValidator -> traceLogger -> AgentOutput
\`\`\`

## Extension Points

- Add tools in \`src/tools/\` and export them from \`src/tools/index.ts\`.
- Replace \`src/model/mockLLM.ts\` with a provider implementing \`ModelProvider\`.
- Extend guard behavior in \`src/agent/guard.ts\`.
- Extend planning in \`src/agent/planner.ts\`.

Trace files are written to \`.agent-traces/<traceId>.json\`.
`;
}

function agentConfig(projectName: string): string {
  return `import type { AgentConfig } from './src/types/config.js';

const config: AgentConfig = {
  name: '${projectName}',
  template: 'tool-agent',
  version: '0.1.0',
  model: {
    provider: 'mock',
    defaultModel: 'mock-basic',
    timeoutMs: 10000,
    maxRetries: 1,
  },
  tools: {
    enabled: [
      // agent-creator:tools
      'weather.query',
      'math.calculate',
    ],
    defaultTimeoutMs: 5000,
    defaultRetry: 1,
  },
  constraints: {
    blockedKeywords: ['伪造凭证', '色情', '投资建议'],
  },
  trace: {
    enabled: true,
    writeToFile: true,
    directory: '.agent-traces',
  },
};

export default config;
`;
}

function sourceIndex(): string {
  return `export { runAgent } from './agent/orchestrator.js';
export type { AgentInput, AgentOutput } from './types/agent.js';
`;
}

function devConsole(): string {
  return `import readline from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';
import config from '../agent.config.js';
import { runAgent } from './agent/orchestrator.js';

const rl = readline.createInterface({ input, output });
const sessionId = \`session_\${Date.now()}\`;

console.log(\`\${config.name} Dev Console started.\`);
console.log('Type "exit" or "quit" to quit.\\n');

while (true) {
  const text = await rl.question('User: ');
  if (['exit', 'quit'].includes(text.trim().toLowerCase())) break;
  const result = await runAgent({ input: text, sessionId });
  console.log('Agent:');
  console.log(JSON.stringify(result, null, 2));
}

rl.close();
`;
}

function agentTypes(): string {
  return `export interface AgentInput {
  input: string;
  userId?: string;
  sessionId?: string;
  metadata?: Record<string, unknown>;
}

export interface AnalyzedInput {
  rawInput: string;
  normalizedInput: string;
  detectedEntities: Record<string, unknown>;
  missingFields: string[];
  riskFlags: string[];
}

export interface AgentIntent {
  name: 'generate_response' | 'call_tool' | 'ask_clarification' | 'safe_redirect';
  confidence: number;
  reason?: string;
}

export interface AgentPlan {
  goal: string;
  steps: AgentPlanStep[];
}

export interface AgentPlanStep {
  id: string;
  type: 'llm' | 'tool' | 'memory' | 'guard';
  name: string;
  input: unknown;
  retry?: number;
  timeoutMs?: number;
}

export interface AgentOutput {
  success: boolean;
  intent: string;
  message: string;
  data?: unknown;
  warnings?: string[];
  errors?: string[];
  traceId?: string;
}

export interface AgentContext {
  input: AgentInput;
  analyzedInput: AnalyzedInput;
  intent: AgentIntent;
  availableTools: string[];
}
`;
}

function toolTypes(): string {
  return `import type { z } from 'zod';

export interface ToolContext {
  traceId: string;
  sessionId?: string;
}

export interface ToolDefinition {
  name: string;
  description: string;
  inputSchema: z.ZodSchema;
  outputSchema: z.ZodSchema;
  permission: 'public' | 'external_api' | 'user_private';
  timeoutMs: number;
  retry: number;
  handler: (input: unknown, context: ToolContext) => Promise<unknown>;
}
`;
}

function configTypes(): string {
  return `export interface AgentConfig {
  name: string;
  template: 'tool-agent';
  version: string;
  model: {
    provider: 'mock';
    defaultModel: string;
    timeoutMs: number;
    maxRetries: number;
  };
  tools: {
    enabled: string[];
    defaultTimeoutMs: number;
    defaultRetry: number;
  };
  constraints: {
    blockedKeywords: string[];
  };
  trace: {
    enabled: boolean;
    writeToFile: boolean;
    directory: string;
  };
}
`;
}

function traceTypes(): string {
  return `import type { AgentIntent, AgentOutput, AgentPlan } from './agent.js';

export interface TraceRecord {
  traceId: string;
  requestId: string;
  startedAt: string;
  endedAt?: string;
  latencyMs?: number;
  userInput: string;
  detectedIntent?: AgentIntent;
  plan?: AgentPlan;
  toolCalls?: unknown[];
  toolResults?: unknown[];
  finalOutput?: AgentOutput;
  errors?: unknown[];
}
`;
}

function outputSchema(): string {
  return `import { z } from 'zod';

export const agentOutputSchema = z.object({
  success: z.boolean(),
  intent: z.string().min(1),
  message: z.string().min(1),
  data: z.unknown().optional(),
  warnings: z.array(z.string()).optional(),
  errors: z.array(z.string()).optional(),
  traceId: z.string().optional(),
});
`;
}

function configSchema(): string {
  return `import { z } from 'zod';

export const agentConfigSchema = z.object({
  name: z.string().min(1),
  template: z.literal('tool-agent'),
  version: z.string().min(1),
  model: z.object({
    provider: z.literal('mock'),
    defaultModel: z.string().min(1),
    timeoutMs: z.number().positive(),
    maxRetries: z.number().int().nonnegative(),
  }),
  tools: z.object({
    enabled: z.array(z.string().min(1)),
    defaultTimeoutMs: z.number().positive(),
    defaultRetry: z.number().int().nonnegative(),
  }),
  constraints: z.object({
    blockedKeywords: z.array(z.string()),
  }),
  trace: z.object({
    enabled: z.boolean(),
    writeToFile: z.boolean(),
    directory: z.string().min(1),
  }),
});
`;
}

function inputAnalyzer(): string {
  return `import config from '../../agent.config.js';
import type { AgentInput, AnalyzedInput } from '../types/agent.js';

export function analyzeInput(input: AgentInput): AnalyzedInput {
  const normalizedInput = input.input.trim();
  const detectedEntities: Record<string, unknown> = {};
  const missingFields: string[] = [];
  const riskFlags: string[] = [];

  if (!normalizedInput) missingFields.push('input');
  if (/天气|weather/i.test(normalizedInput)) detectedEntities.possibleTool = 'weather.query';
  if (/计算|calculate|[+\\-*/()]/i.test(normalizedInput)) detectedEntities.possibleTool = 'math.calculate';

  for (const keyword of config.constraints.blockedKeywords) {
    if (normalizedInput.includes(keyword)) riskFlags.push(keyword);
  }

  return { rawInput: input.input, normalizedInput, detectedEntities, missingFields, riskFlags };
}
`;
}

function intentRouter(): string {
  return `import type { AnalyzedInput, AgentIntent } from '../types/agent.js';

export function routeIntent(input: AnalyzedInput): AgentIntent {
  if (input.missingFields.includes('input')) {
    return { name: 'ask_clarification', confidence: 1, reason: 'Input is empty.' };
  }
  if (input.riskFlags.length > 0) {
    return { name: 'safe_redirect', confidence: 1, reason: 'Input matched blocked keywords.' };
  }
  if (typeof input.detectedEntities.possibleTool === 'string') {
    return { name: 'call_tool', confidence: 0.86, reason: 'Input indicates a tool call.' };
  }
  return { name: 'generate_response', confidence: 0.7, reason: 'Default response intent.' };
}
`;
}

function guard(): string {
  return `import type { AgentIntent, AnalyzedInput } from '../types/agent.js';

export interface GuardResult {
  allowed: boolean;
  reason?: string;
  action: 'continue' | 'safe_redirect';
  warnings?: string[];
}

const allowedIntents = ['generate_response', 'call_tool', 'ask_clarification', 'safe_redirect'];

export function runGuard(analyzedInput: AnalyzedInput, intent: AgentIntent): GuardResult {
  if (!allowedIntents.includes(intent.name)) {
    return { allowed: false, reason: 'Intent is not allowed.', action: 'safe_redirect' };
  }
  if (analyzedInput.riskFlags.length > 0) {
    return {
      allowed: false,
      reason: \`Blocked keyword matched: \${analyzedInput.riskFlags.join(', ')}\`,
      action: 'safe_redirect',
      warnings: analyzedInput.riskFlags,
    };
  }
  return { allowed: true, action: 'continue' };
}
`;
}

function planner(): string {
  return `import type { AgentContext, AgentPlan } from '../types/agent.js';
import { createId } from '../utils/id.js';

export function createPlan(context: AgentContext): AgentPlan {
  if (context.intent.name === 'safe_redirect') {
    return { goal: 'Return safe redirect', steps: [{ id: createId('step'), type: 'guard', name: 'safe_redirect', input: {} }] };
  }
  if (context.intent.name === 'ask_clarification') {
    return { goal: 'Ask clarification', steps: [{ id: createId('step'), type: 'llm', name: 'ask_clarification', input: context.input.input }] };
  }
  if (context.intent.name === 'call_tool') {
    const toolName = String(context.analyzedInput.detectedEntities.possibleTool);
    const input = toolName === 'math.calculate'
      ? { expression: extractExpression(context.analyzedInput.normalizedInput) }
      : { location: extractLocation(context.analyzedInput.normalizedInput), date: 'tomorrow' };
    return { goal: \`Call \${toolName} tool\`, steps: [{ id: createId('step'), type: 'tool', name: toolName, input }] };
  }
  return { goal: 'Generate response', steps: [{ id: createId('step'), type: 'llm', name: 'generate_response', input: context.input.input }] };
}

function extractExpression(input: string): string {
  const match = input.match(/[0-9\\s+\\-*/().]+/);
  return match?.[0]?.trim() || '1 + 1';
}

function extractLocation(input: string): string {
  const words = input.split(/\\s+/).filter(Boolean);
  return words.find((word) => !/天气|weather|明天|tomorrow/i.test(word)) || 'Tokyo';
}
`;
}

function executor(): string {
  return `import type { AgentOutput, AgentPlan } from '../types/agent.js';
import type { TraceLogger } from '../traces/traceLogger.js';
import { getToolRegistry } from './toolRegistry.js';
import { recoverError } from './errorRecovery.js';
import { mockLLM } from '../model/mockLLM.js';

export async function executePlan(plan: AgentPlan, traceId: string, sessionId: string | undefined, trace: TraceLogger): Promise<AgentOutput> {
  for (const step of plan.steps) {
    try {
      if (step.type === 'guard') {
        return { success: false, intent: 'safe_redirect', message: 'Sorry, I cannot complete that request safely.', traceId };
      }
      if (step.type === 'tool') {
        trace.append({ toolCalls: [{ name: step.name, input: step.input }] });
        const data = await getToolRegistry().executeTool(step.name, step.input, { traceId, sessionId });
        trace.append({ toolResults: [{ name: step.name, data }] });
        return { success: true, intent: 'call_tool', message: \`Tool \${step.name} executed successfully.\`, data, traceId };
      }
      if (step.type === 'llm') {
        const result = await mockLLM.generate({ task: step.name, input: step.input });
        return { success: true, intent: step.name, message: result.text, data: result.data, traceId };
      }
    } catch (error) {
      const recovered = recoverError(error);
      if (recovered.output) return { ...recovered.output, traceId };
      return { success: false, intent: step.name, message: recovered.reason, errors: [recovered.reason], traceId };
    }
  }
  return { success: false, intent: 'unknown', message: 'No executable plan steps found.', traceId };
}
`;
}

function orchestrator(): string {
  return `import config from '../../agent.config.js';
import type { AgentInput, AgentOutput, AgentContext } from '../types/agent.js';
import { analyzeInput } from './inputAnalyzer.js';
import { routeIntent } from './intentRouter.js';
import { runGuard } from './guard.js';
import { createPlan } from './planner.js';
import { executePlan } from './executor.js';
import { validateOutput } from './outputValidator.js';
import { createTraceLogger } from '../traces/traceLogger.js';
import { createId } from '../utils/id.js';
import { getToolRegistry } from './toolRegistry.js';

export async function runAgent(input: AgentInput): Promise<AgentOutput> {
  const traceId = createId('trace');
  const requestId = createId('req');
  const trace = createTraceLogger(config.trace, traceId, requestId, input.input);

  try {
    const analyzedInput = analyzeInput(input);
    const intent = routeIntent(analyzedInput);
    trace.append({ detectedIntent: intent });

    const guard = runGuard(analyzedInput, intent);
    const effectiveIntent = guard.allowed ? intent : { name: 'safe_redirect' as const, confidence: 1, reason: guard.reason };

    const context: AgentContext = {
      input,
      analyzedInput,
      intent: effectiveIntent,
      availableTools: getToolRegistry().listTools().map((tool) => tool.name),
    };

    const plan = createPlan(context);
    trace.append({ plan });
    const output = await executePlan(plan, traceId, input.sessionId, trace);
    const validated = validateOutput(output, traceId);
    trace.end(validated);
    return validated;
  } catch (error) {
    const fallback = validateOutput({
      success: false,
      intent: 'unknown_error',
      message: 'Agent recovered from an unexpected error.',
      errors: [error instanceof Error ? error.message : String(error)],
      traceId,
    }, traceId);
    trace.append({ errors: [fallback.errors] });
    trace.end(fallback);
    return fallback;
  }
}
`;
}

function toolRegistry(): string {
  return `import type { ToolContext, ToolDefinition } from '../types/tool.js';
import { weatherTool } from '../tools/weather.js';
import { mathTool } from '../tools/math.js';

export class ToolRegistry {
  private tools = new Map<string, ToolDefinition>();

  registerTool(tool: ToolDefinition): void {
    this.tools.set(tool.name, tool);
  }

  getTool(name: string): ToolDefinition {
    const tool = this.tools.get(name);
    if (!tool) throw new Error(\`tool_not_found: \${name}\`);
    return tool;
  }

  listTools(): ToolDefinition[] {
    return [...this.tools.values()];
  }

  hasTool(name: string): boolean {
    return this.tools.has(name);
  }

  async executeTool(name: string, input: unknown, context: ToolContext): Promise<unknown> {
    const tool = this.getTool(name);
    const parsedInput = tool.inputSchema.safeParse(input);
    if (!parsedInput.success) throw new Error(\`tool_input_invalid: \${parsedInput.error.message}\`);
    const output = await tool.handler(parsedInput.data, context);
    const parsedOutput = tool.outputSchema.safeParse(output);
    if (!parsedOutput.success) throw new Error(\`tool_output_invalid: \${parsedOutput.error.message}\`);
    return parsedOutput.data;
  }
}

const registry = new ToolRegistry();
registry.registerTool(weatherTool);
registry.registerTool(mathTool);

export function getToolRegistry(): ToolRegistry {
  return registry;
}
`;
}

function outputValidator(): string {
  return `import type { AgentOutput } from '../types/agent.js';
import { agentOutputSchema } from '../schemas/output.schema.js';

export function validateOutput(output: AgentOutput, traceId: string): AgentOutput {
  const parsed = agentOutputSchema.safeParse(output);
  if (parsed.success) return parsed.data;
  return {
    success: false,
    intent: output.intent || 'output_invalid',
    message: output.message || 'Output validation failed.',
    errors: [parsed.error.message],
    traceId,
  };
}
`;
}

function errorRecovery(): string {
  return `import type { AgentOutput } from '../types/agent.js';

export interface RecoveryResult {
  recovered: boolean;
  output?: AgentOutput;
  retry?: boolean;
  fallback?: boolean;
  reason: string;
}

export function recoverError(error: unknown): RecoveryResult {
  const message = error instanceof Error ? error.message : String(error);
  if (message.startsWith('tool_not_found')) return { recovered: true, reason: message, fallback: true };
  if (message.startsWith('tool_input_invalid')) return { recovered: true, reason: message, fallback: true };
  if (message.startsWith('tool_output_invalid')) return { recovered: true, reason: message, fallback: true };
  return { recovered: true, reason: \`unknown_error: \${message}\`, fallback: true };
}
`;
}

function modelProvider(): string {
  return `export interface ModelGenerateInput {
  task: string;
  input: unknown;
}

export interface ModelGenerateOutput {
  text: string;
  data?: unknown;
}

export interface ModelProvider {
  generate(input: ModelGenerateInput): Promise<ModelGenerateOutput>;
}
`;
}

function mockLLM(): string {
  return `import type { ModelProvider } from './modelProvider.js';

export const mockLLM: ModelProvider = {
  async generate(input) {
    if (input.task === 'ask_clarification') {
      return { text: 'What would you like the agent to help with?' };
    }
    if (input.task === 'safe_redirect') {
      return { text: 'Sorry, I cannot complete that request safely.' };
    }
    return { text: \`Mock response for: \${String(input.input)}\` };
  },
};
`;
}

function memoryManager(): string {
  return `const sessions = new Map<string, unknown[]>();

export function appendSessionMessage(sessionId: string, message: unknown): void {
  const current = sessions.get(sessionId) ?? [];
  current.push(message);
  sessions.set(sessionId, current);
}

export function getSession(sessionId: string): unknown[] {
  return sessions.get(sessionId) ?? [];
}

export function clearMemory(sessionId?: string): void {
  if (sessionId) sessions.delete(sessionId);
  else sessions.clear();
}
`;
}

function toolsIndex(): string {
  return `export { weatherTool } from './weather.js';
export { mathTool } from './math.js';

export const enabledTools = [
  // agent-creator:tool-exports
  'weather.query',
  'math.calculate',
];
`;
}

function weatherTool(): string {
  return `import { z } from 'zod';
import type { ToolDefinition } from '../types/tool.js';

const inputSchema = z.object({
  location: z.string().min(1),
  date: z.string().min(1),
});

const outputSchema = z.object({
  location: z.string(),
  date: z.string(),
  condition: z.string(),
  temperature: z.number(),
});

export const weatherTool: ToolDefinition = {
  name: 'weather.query',
  description: 'Return mock weather for a location and date.',
  inputSchema,
  outputSchema,
  permission: 'public',
  timeoutMs: 5000,
  retry: 1,
  async handler(input) {
    const value = inputSchema.parse(input);
    return {
      location: value.location,
      date: value.date,
      condition: 'rainy',
      temperature: 22,
    };
  },
};
`;
}

function mathTool(): string {
  return `import { z } from 'zod';
import type { ToolDefinition } from '../types/tool.js';

const inputSchema = z.object({ expression: z.string().min(1) });
const outputSchema = z.object({ expression: z.string(), result: z.number() });

export const mathTool: ToolDefinition = {
  name: 'math.calculate',
  description: 'Safely evaluate basic arithmetic without eval.',
  inputSchema,
  outputSchema,
  permission: 'public',
  timeoutMs: 5000,
  retry: 1,
  async handler(input) {
    const value = inputSchema.parse(input);
    return { expression: value.expression, result: evaluateExpression(value.expression) };
  },
};

function evaluateExpression(expression: string): number {
  if (!/^[0-9+\\-*/().\\s]+$/.test(expression)) throw new Error('Only numbers and + - * / ( ) are allowed.');
  const tokens = expression.match(/\\d+(?:\\.\\d+)?|[()+\\-*/]/g) ?? [];
  let index = 0;

  function parseExpression(): number {
    let value = parseTerm();
    while (tokens[index] === '+' || tokens[index] === '-') {
      const op = tokens[index++];
      const right = parseTerm();
      value = op === '+' ? value + right : value - right;
    }
    return value;
  }

  function parseTerm(): number {
    let value = parseFactor();
    while (tokens[index] === '*' || tokens[index] === '/') {
      const op = tokens[index++];
      const right = parseFactor();
      if (op === '/' && right === 0) throw new Error('Division by zero.');
      value = op === '*' ? value * right : value / right;
    }
    return value;
  }

  function parseFactor(): number {
    const token = tokens[index++];
    if (!token) throw new Error('Unexpected end of expression.');
    if (token === '(') {
      const value = parseExpression();
      if (tokens[index++] !== ')') throw new Error('Expected closing parenthesis.');
      return value;
    }
    if (token === '-') return -parseFactor();
    const value = Number(token);
    if (Number.isNaN(value)) throw new Error(\`Invalid token: \${token}\`);
    return value;
  }

  const result = parseExpression();
  if (index < tokens.length) throw new Error('Unexpected token after expression.');
  return result;
}
`;
}

function traceLogger(): string {
  return `import type { AgentOutput } from '../types/agent.js';
import type { TraceRecord } from '../types/trace.js';
import type { AgentConfig } from '../types/config.js';
import { writeTrace } from './traceStore.js';

export interface TraceLogger {
  append(patch: Partial<TraceRecord>): void;
  end(output: AgentOutput): void;
}

export function createTraceLogger(config: AgentConfig['trace'], traceId: string, requestId: string, userInput: string): TraceLogger {
  const started = Date.now();
  const record: TraceRecord = {
    traceId,
    requestId,
    startedAt: new Date(started).toISOString(),
    userInput,
  };

  return {
    append(patch) {
      Object.assign(record, patch);
    },
    end(output) {
      const ended = Date.now();
      record.endedAt = new Date(ended).toISOString();
      record.latencyMs = ended - started;
      record.finalOutput = output;
      if (config.enabled && config.writeToFile) {
        void writeTrace(config.directory, record);
      }
    },
  };
}
`;
}

function traceStore(): string {
  return `import fs from 'node:fs/promises';
import path from 'node:path';
import type { TraceRecord } from '../types/trace.js';

export async function writeTrace(directory: string, record: TraceRecord): Promise<void> {
  await fs.mkdir(directory, { recursive: true });
  await fs.writeFile(path.join(directory, \`\${record.traceId}.json\`), JSON.stringify(record, null, 2), 'utf8');
}
`;
}

function idUtil(): string {
  return `export function createId(prefix: string): string {
  return \`\${prefix}_\${Date.now()}_\${Math.random().toString(36).slice(2, 8)}\`;
}
`;
}

function timeUtil(): string {
  return `export function nowIso(): string {
  return new Date().toISOString();
}
`;
}

function jsonUtil(): string {
  return `export function safeJson(value: unknown): string {
  return JSON.stringify(value, null, 2);
}
`;
}

function errorsUtil(): string {
  return `export function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}
`;
}

function loggerUtil(): string {
  return `export const logger = {
  info: console.log,
  error: console.error,
};
`;
}

function configTest(): string {
  return `import { describe, expect, it } from 'vitest';
import config from '../agent.config.js';
import { agentConfigSchema } from '../src/schemas/config.schema.js';

describe('config', () => {
  it('matches the config schema', () => {
    expect(agentConfigSchema.safeParse(config).success).toBe(true);
  });
});
`;
}

function toolRegistryTest(): string {
  return `import { describe, expect, it } from 'vitest';
import { getToolRegistry } from '../src/agent/toolRegistry.js';

describe('tool registry', () => {
  it('executes weather.query', async () => {
    const result = await getToolRegistry().executeTool('weather.query', { location: 'Tokyo', date: 'tomorrow' }, { traceId: 'test' });
    expect(result).toMatchObject({ location: 'Tokyo', condition: 'rainy' });
  });

  it('executes math.calculate', async () => {
    const result = await getToolRegistry().executeTool('math.calculate', { expression: '1 + 2 * 3' }, { traceId: 'test' });
    expect(result).toMatchObject({ result: 7 });
  });

  it('rejects unsafe math', async () => {
    await expect(getToolRegistry().executeTool('math.calculate', { expression: 'process.exit()' }, { traceId: 'test' })).rejects.toThrow();
  });
});
`;
}

function orchestratorTest(): string {
  return `import { describe, expect, it } from 'vitest';
import { runAgent } from '../src/agent/orchestrator.js';

describe('orchestrator', () => {
  it('returns generate_response for normal input', async () => {
    const result = await runAgent({ input: 'hello' });
    expect(result.intent).toBe('generate_response');
    expect(result.traceId).toBeTruthy();
  });

  it('calls weather.query', async () => {
    const result = await runAgent({ input: 'Tokyo weather tomorrow' });
    expect(result.intent).toBe('call_tool');
    expect(result.data).toMatchObject({ location: 'Tokyo' });
  });

  it('calls math.calculate', async () => {
    const result = await runAgent({ input: 'calculate 1 + 2 * 3' });
    expect(result.data).toMatchObject({ result: 7 });
  });

  it('asks clarification for empty input', async () => {
    const result = await runAgent({ input: '   ' });
    expect(result.intent).toBe('ask_clarification');
  });

  it('safe redirects blocked keywords', async () => {
    const result = await runAgent({ input: '请给我投资建议' });
    expect(result.intent).toBe('safe_redirect');
  });
});
`;
}

function exampleBasic(): string {
  return `import { runAgent } from '../src/index.js';

console.log(await runAgent({ input: 'hello agent' }));
`;
}

function exampleToolCall(): string {
  return `import { runAgent } from '../src/index.js';

console.log(await runAgent({ input: 'calculate 40 + 2' }));
`;
}
