import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { createCommand } from '../src/commands/create.js';
import { CLI_VERSION } from '../src/version.js';

describe('create command', () => {
  it('creates an agent-core project', async () => {
    const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'agent-creator-'));
    const previous = process.cwd();
    process.chdir(dir);
    try {
      await createCommand('demo-agent', { capability: 'agent-core', packageManager: 'npm' });
      await expect(fs.access(path.join(dir, 'demo-agent', 'agent.config.ts'))).resolves.toBeUndefined();
      await expect(fs.access(path.join(dir, 'demo-agent', 'src/cli.ts'))).resolves.toBeUndefined();
      await expect(fs.access(path.join(dir, 'demo-agent', 'src/env.ts'))).resolves.toBeUndefined();
      await expect(fs.access(path.join(dir, 'demo-agent', '.env.example'))).resolves.toBeUndefined();
      await expect(fs.access(path.join(dir, 'demo-agent', 'docs/api.md'))).resolves.toBeUndefined();
      await expect(fs.access(path.join(dir, 'demo-agent', 'src/client.ts'))).resolves.toBeUndefined();
      await expect(fs.access(path.join(dir, 'demo-agent', 'src/skills/index.ts'))).resolves.toBeUndefined();
      await expect(fs.access(path.join(dir, 'demo-agent', 'src/guards/index.ts'))).resolves.toBeUndefined();
      await expect(fs.access(path.join(dir, 'demo-agent', 'src/agent/orchestrator.ts'))).rejects.toThrow();
      await expect(fs.access(path.join(dir, 'demo-agent', 'src/app/page.tsx'))).resolves.toBeUndefined();
      await expect(fs.access(path.join(dir, 'demo-agent', 'src/app/api/agent/route.ts'))).resolves.toBeUndefined();
      await expect(fs.access(path.join(dir, 'demo-agent', 'src/app/api/agent/auth.ts'))).resolves.toBeUndefined();
      await expect(fs.access(path.join(dir, 'demo-agent', 'src/app/api/agent/health/route.ts'))).resolves.toBeUndefined();
      await expect(fs.access(path.join(dir, 'demo-agent', 'src/app/api/agent/stream/route.ts'))).resolves.toBeUndefined();
      const config = await fs.readFile(path.join(dir, 'demo-agent', 'agent.config.ts'), 'utf8');
      expect(config).toContain("capability: 'agent-core'");
      expect(config).toContain("configVersion: '0.1'");
      expect(config).toContain('enabled: true');
      expect(config).toContain("framework: 'next'");
      expect(config).toContain(`capabilityVersion: '${CLI_VERSION}'`);
      expect(config).toContain("generatedBy:");
      expect(config).toContain("baseUrl: process.env.LLM_BASE_URL ?? ''");
      expect(config).toContain("apiKey: process.env.OPENAI_API_KEY ?? ''");
      expect(config).toContain("model: process.env.LLM_MODEL ?? 'gpt-4o-mini'");
      expect(config).toContain("url: process.env.WEBHOOK_URL ?? ''");
      expect(config).toContain('guards:');
      expect(config).toContain('workflows:');
      const readme = await fs.readFile(path.join(dir, 'demo-agent', 'README.md'), 'utf8');
      expect(readme).toContain(`Generated by Agent Creator v${CLI_VERSION}.`);
      expect(readme).toContain('5 Minute Integration');
      expect(readme).toContain('docs/api.md');
      expect(readme).toContain('/api/agent/health');
      expect(readme).toContain('set the minimum model configuration');
      expect(readme).toContain('Service mode starts a Next.js web chat');
      const envExample = await fs.readFile(path.join(dir, 'demo-agent', '.env.example'), 'utf8');
      expect(envExample).toContain('LLM_BASE_URL=https://api.openai.com/v1');
      expect(envExample).toContain('OPENAI_API_KEY=your-openai-api-key');
      expect(envExample).toContain('WEBHOOK_URL=');
      expect(envExample).toContain('AGENT_API_KEY=');
      const apiDocs = await fs.readFile(path.join(dir, 'demo-agent', 'docs/api.md'), 'utf8');
      expect(apiDocs).toContain('POST /api/agent');
      expect(apiDocs).toContain('POST /api/agent/stream');
      expect(apiDocs).toContain('GET /api/agent/health');
      expect(apiDocs).toContain('application/x-ndjson');
      const client = await fs.readFile(path.join(dir, 'demo-agent', 'src/client.ts'), 'utf8');
      expect(client).toContain('runAgentHttp');
      expect(client).toContain('streamAgentHttp');
      const index = await fs.readFile(path.join(dir, 'demo-agent', 'src/index.ts'), 'utf8');
      expect(index).toContain('webhook: config.webhook');
      expect(index).toContain('builder.useGuard(guard)');
      const generatedPackageJson = JSON.parse(await fs.readFile(path.join(dir, 'demo-agent', 'package.json'), 'utf8')) as {
        version: string;
        dependencies: Record<string, string>;
        scripts: Record<string, string>;
        exports: Record<string, { import: string; types: string }>;
      };
      expect(generatedPackageJson.version).toBe(CLI_VERSION);
      expect(generatedPackageJson.dependencies).toHaveProperty('next');
      expect(generatedPackageJson.dependencies).toHaveProperty('antd');
      expect(generatedPackageJson.dependencies).toHaveProperty('@agent-creator/core');
      expect(generatedPackageJson.scripts.dev).toBe('next dev');
      expect(generatedPackageJson.scripts['dev:agent']).toBe('tsx src/cli.ts');
      expect(generatedPackageJson.exports['./client'].import).toBe('./dist/src/client.js');
      const cli = await fs.readFile(path.join(dir, 'demo-agent', 'src/cli.ts'), 'utf8');
      expect(cli).toContain('onProgress');
      const route = await fs.readFile(path.join(dir, 'demo-agent', 'src/app/api/agent/route.ts'), 'utf8');
      expect(route).toContain('requireAgentApiKey');
      const streamRoute = await fs.readFile(path.join(dir, 'demo-agent', 'src/app/api/agent/stream/route.ts'), 'utf8');
      expect(streamRoute).toContain('requireAgentApiKey');
      const auth = await fs.readFile(path.join(dir, 'demo-agent', 'src/app/api/agent/auth.ts'), 'utf8');
      expect(auth).toContain('process.env.AGENT_API_KEY');
      expect(auth).toContain('if (!expected) return undefined');
      expect(auth).toContain('authorization');
      expect(auth).toContain('if (actual === expected) return undefined');
      expect(auth).toContain('status: 401');
      const health = await fs.readFile(path.join(dir, 'demo-agent', 'src/app/api/agent/health/route.ts'), 'utf8');
      expect(health).toContain('baseUrlConfigured');
      expect(health).toContain('apiKeyConfigured');
      const chat = await fs.readFile(path.join(dir, 'demo-agent', 'src/components/AgentChat.tsx'), 'utf8');
      expect(chat).toContain('/api/agent/stream');
    } finally {
      process.chdir(previous);
    }
  });

  it('creates a package-mode agent-core without service files or dependencies', async () => {
    const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'agent-creator-'));
    const previous = process.cwd();
    process.chdir(dir);
    try {
      await createCommand('demo-agent', { capability: 'agent-core', packageManager: 'npm', mode: 'package' });
      await expect(fs.access(path.join(dir, 'demo-agent', 'src/index.ts'))).resolves.toBeUndefined();
      await expect(fs.access(path.join(dir, 'demo-agent', 'src/cli.ts'))).resolves.toBeUndefined();
      await expect(fs.access(path.join(dir, 'demo-agent', 'src/env.ts'))).resolves.toBeUndefined();
      await expect(fs.access(path.join(dir, 'demo-agent', '.env.example'))).resolves.toBeUndefined();
      await expect(fs.access(path.join(dir, 'demo-agent', 'docs/api.md'))).resolves.toBeUndefined();
      await expect(fs.access(path.join(dir, 'demo-agent', 'src/client.ts'))).resolves.toBeUndefined();
      await expect(fs.access(path.join(dir, 'demo-agent', 'src/app/page.tsx'))).rejects.toThrow();
      await expect(fs.access(path.join(dir, 'demo-agent', 'next.config.ts'))).rejects.toThrow();
      await expect(fs.access(path.join(dir, 'demo-agent', 'src/app/api/agent/health/route.ts'))).rejects.toThrow();

      const config = await fs.readFile(path.join(dir, 'demo-agent', 'agent.config.ts'), 'utf8');
      expect(config).toContain('enabled: false');
      expect(config).toContain('framework: undefined');
      expect(config).toContain("model: process.env.LLM_MODEL ?? 'gpt-4o-mini'");
      expect(config).toContain("url: process.env.WEBHOOK_URL ?? ''");
      expect(config).toContain('guards:');
      expect(config).toContain('workflows:');

      const generatedPackageJson = JSON.parse(await fs.readFile(path.join(dir, 'demo-agent', 'package.json'), 'utf8')) as {
        bin: Record<string, string>;
        dependencies: Record<string, string>;
        exports: Record<string, { import: string; types: string }>;
        scripts: Record<string, string>;
      };
      expect(generatedPackageJson.dependencies).not.toHaveProperty('next');
      expect(generatedPackageJson.dependencies).not.toHaveProperty('antd');
      expect(generatedPackageJson.dependencies).toHaveProperty('@agent-creator/core');
      expect(generatedPackageJson.bin['demo-agent']).toBe('./dist/src/cli.js');
      expect(generatedPackageJson.exports['./client'].import).toBe('./dist/src/client.js');
      expect(generatedPackageJson.scripts.dev).toBe('tsx src/cli.ts');
      expect(generatedPackageJson.scripts.start).toBe('node dist/src/cli.js');
      expect(generatedPackageJson.scripts).not.toHaveProperty('dev:agent');
      const cli = await fs.readFile(path.join(dir, 'demo-agent', 'src/cli.ts'), 'utf8');
      expect(cli).toContain('loadDotEnv');
      expect(cli).toContain('onProgress');
      expect(cli).toContain('Set model.baseUrl and model.apiKey in agent.config.ts');
      expect(cli).not.toContain('LLM_MODEL before running');
    } finally {
      process.chdir(previous);
    }
  });

  it('rejects unsupported create modes', async () => {
    await expect(createCommand('demo-agent', { capability: 'agent-core', packageManager: 'npm', mode: 'mobile' })).rejects.toThrow('Unsupported create mode');
  });
});
