import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { createCommand } from '../src/commands/create.js';
import { CLI_VERSION } from '../src/version.js';

describe('create command', () => {
  it('creates an agent-core project', async () => {
    const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'agent-creator-'));
    const previous = process.cwd();
    process.chdir(dir);
    try {
      await createCommand('demo-agent', { capability: 'agent-core', packageManager: 'npm' });
      await expect(fs.access(path.join(dir, 'demo-agent', 'agent.config.ts'))).resolves.toBeUndefined();
      await expect(fs.access(path.join(dir, 'demo-agent', 'src/skills/index.ts'))).resolves.toBeUndefined();
      await expect(fs.access(path.join(dir, 'demo-agent', 'src/agent/orchestrator.ts'))).rejects.toThrow();
      await expect(fs.access(path.join(dir, 'demo-agent', 'src/app/page.tsx'))).resolves.toBeUndefined();
      await expect(fs.access(path.join(dir, 'demo-agent', 'src/app/api/agent/route.ts'))).resolves.toBeUndefined();
      const config = await fs.readFile(path.join(dir, 'demo-agent', 'agent.config.ts'), 'utf8');
      expect(config).toContain("capability: 'agent-core'");
      expect(config).toContain("configVersion: '0.1'");
      expect(config).toContain('enabled: true');
      expect(config).toContain("framework: 'next'");
      expect(config).toContain(`capabilityVersion: '${CLI_VERSION}'`);
      expect(config).toContain("generatedBy:");
      const readme = await fs.readFile(path.join(dir, 'demo-agent', 'README.md'), 'utf8');
      expect(readme).toContain(`Generated by Agent Creator v${CLI_VERSION}.`);
      const generatedPackageJson = JSON.parse(await fs.readFile(path.join(dir, 'demo-agent', 'package.json'), 'utf8')) as {
        version: string;
        dependencies: Record<string, string>;
        scripts: Record<string, string>;
      };
      expect(generatedPackageJson.version).toBe(CLI_VERSION);
      expect(generatedPackageJson.dependencies).toHaveProperty('next');
      expect(generatedPackageJson.dependencies).toHaveProperty('antd');
      expect(generatedPackageJson.dependencies).toHaveProperty('@agent-creator/core');
      expect(generatedPackageJson.scripts.dev).toBe('next dev');
      expect(generatedPackageJson.scripts['dev:agent']).toBe('tsx src/dev.ts');
    } finally {
      process.chdir(previous);
    }
  });

  it('creates a package-mode agent-core without service files or dependencies', async () => {
    const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'agent-creator-'));
    const previous = process.cwd();
    process.chdir(dir);
    try {
      await createCommand('demo-agent', { capability: 'agent-core', packageManager: 'npm', mode: 'package' });
      await expect(fs.access(path.join(dir, 'demo-agent', 'src/index.ts'))).resolves.toBeUndefined();
      await expect(fs.access(path.join(dir, 'demo-agent', 'src/app/page.tsx'))).rejects.toThrow();
      await expect(fs.access(path.join(dir, 'demo-agent', 'next.config.ts'))).rejects.toThrow();

      const config = await fs.readFile(path.join(dir, 'demo-agent', 'agent.config.ts'), 'utf8');
      expect(config).toContain('enabled: false');
      expect(config).toContain('framework: undefined');

      const generatedPackageJson = JSON.parse(await fs.readFile(path.join(dir, 'demo-agent', 'package.json'), 'utf8')) as {
        dependencies: Record<string, string>;
        scripts: Record<string, string>;
      };
      expect(generatedPackageJson.dependencies).not.toHaveProperty('next');
      expect(generatedPackageJson.dependencies).not.toHaveProperty('antd');
      expect(generatedPackageJson.dependencies).toHaveProperty('@agent-creator/core');
      expect(generatedPackageJson.scripts.dev).toBe('tsx src/dev.ts');
      expect(generatedPackageJson.scripts).not.toHaveProperty('dev:agent');
    } finally {
      process.chdir(previous);
    }
  });

  it('rejects unsupported create modes', async () => {
    await expect(createCommand('demo-agent', { capability: 'agent-core', packageManager: 'npm', mode: 'mobile' })).rejects.toThrow('Unsupported create mode');
  });
});
